scrapy crawl  Zhejiang
scrapy crawl  Jiangxi
scrapy crawl  Fujian
scrapy crawl  Sichuan
scrapy crawl  Heilongjiang
scrapy crawl  Ningxia
scrapy crawl  Guizhou
scrapy crawl  Guangxi
scrapy crawl  Xinjiang
scrapy crawl  Jiangsu
scrapy crawl  Shandong
scrapy crawl  Hebei
scrapy crawl  Jilin
scrapy crawl  Shanghai
scrapy crawl  Gansu
scrapy crawl  Henan
scrapy crawl  Qinghai
scrapy crawl  Xizang
scrapy crawl  Central
scrapy crawl  Tianjin
scrapy crawl  Anhui
scrapy crawl  Neimenggu
scrapy crawl  Guangdong
scrapy crawl  Shaanxi_shan
scrapy crawl  Chongqing
scrapy crawl  Liaoning
scrapy crawl  Hunan
scrapy crawl  Beijing
scrapy crawl  Shanxi_jin
scrapy crawl  Hainan
scrapy crawl  Yunnan
